{
 "title": "kPerf Monitor",
 "time": { "from": "2025-07-29T05:22:35.360Z", "to": "2025-07-29T05:29:06.794Z" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "SYSTEM_EVENT_CLASS",
    "label": "SYSTEM_EVENT_CLASS_WAITS",
    "query": {
     "query": "label_values(lSYSTEM_EVENT_CLASS)"
    }
   },
   {
    "name": "SYSTEM_EVENT_WAIT_COUNT",
    "label": "SYSTEM_EVENT_WAIT_COUNT",
    "query": {
     "query": "label_values(lSYSTEM_EVENT_WAIT_COUNT)"
    }
   },
   {
    "name": "SYSTEM_EVENT_WAIT_TIME",
    "label": "SYSTEM_EVENT_WAIT_TIME",
    "query": {
     "query": "label_values(lSYSTEM_EVENT_WAIT_TIME_PER_EVENT)"
    }
   },
   { "name": "SYSSTAT", "label": "SYSSTAT", "query": { "query": "label_values(lSYSSTAT)" } },
   {
    "name": "SYSTEM_EVENT_CLASS_TIME",
    "label": "SYSTEM_EVENT_CLASS_TIME",
    "query": {
     "query": "label_values(lSYSTEM_EVENT_CLASS_TIME)"
    }
   },
   { "name": "vdsname", "label": "vdsname", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "System Events and Stat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Event Class",
   "type": "piechart",
   "description": "SYSTEM_EVENT_CLASS",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(SYSTEM_EVENT_CLASS_TIME{lSYSTEM_EVENT_CLASS_TIME=~\"$SYSTEM_EVENT_CLASS_TIME\",job=\"$job\"})/on() group_left() (sum(SYSTEM_EVENT_CLASS_TIME{lSYSTEM_EVENT_CLASS_TIME=~\"$SYSTEM_EVENT_CLASS_TIME\",job=\"$job\"}))",
     "legendFormat": "{{lSYSTEM_EVENT_CLASS_TIME}}"
    }
   ]
  },
  {
   "title": "System Events Wait TIme per event",
   "type": "timeseries",
   "description": "Длительность каждого(одного) ожидания",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "SYSTEM_EVENT_WAIT_TIME_PER_EVENT{lSYSTEM_EVENT_WAIT_TIME_PER_EVENT=~\"$SYSTEM_EVENT_WAIT_TIME\",job=\"$job\"}",
     "legendFormat": "{{lSYSTEM_EVENT_WAIT_TIME_PER_EVENT}}"
    }
   ]
  },
  {
   "title": "System Event Class",
   "type": "timeseries",
   "description": "SYSTEM_EVENT_CLASS",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(SYSTEM_EVENT_CLASS_TIME{lSYSTEM_EVENT_CLASS_TIME=~\"$SYSTEM_EVENT_CLASS_TIME\",job=\"$job\"})/on() group_left() (sum(SYSTEM_EVENT_CLASS_TIME{lSYSTEM_EVENT_CLASS_TIME=~\"$SYSTEM_EVENT_CLASS_TIME\",job=\"$job\"}))",
     "legendFormat": "{{lSYSTEM_EVENT_CLASS_TIME}}"
    }
   ]
  },
  {
   "title": "System Events Wait Count per sec.",
   "type": "timeseries",
   "description": "Количество   каждого ожидания(одного), за промежуток между снапшотами.  ",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SYSTEM_EVENT_WAIT_COUT{lSYSTEM_EVENT_WAIT_COUNT=~\"$SYSTEM_EVENT_WAIT_COUNT\",job=\"$job\"}",
     "legendFormat": "{{lSYSTEM_EVENT_WAIT_COUNT}}"
    }
   ]
  },
  {
   "title": "System Event Class",
   "type": "table",
   "description": "SYSTEM_EVENT_CLASS",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(SYSTEM_EVENT_CLASS_TIME{lSYSTEM_EVENT_CLASS_TIME=~\"$SYSTEM_EVENT_CLASS_TIME\",job=\"$job\"})/on() group_left() (sum(SYSTEM_EVENT_CLASS_TIME{lSYSTEM_EVENT_CLASS_TIME=~\"$SYSTEM_EVENT_CLASS_TIME\",job=\"$job\"}))",
     "legendFormat": "{{lSYSTEM_EVENT_CLASS_TIME}}"
    }
   ]
  },
  {
   "title": "SysStat statistics",
   "type": "timeseries",
   "description": "Статистики из sysstat(количество коммитов, логонов, выполнений и тд) ",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SYSSTAT{lSYSSTAT=~\"$SYSSTAT\",job=\"$job\"}",
     "legendFormat": "{{lSYSSTAT}}"
    }
   ]
  },
  { "title": "SQL Stat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "SQL exec per sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SQL_EXECUTIONS_PER_SEC{job=\"$job\"}",
     "legendFormat": "SQLD: {{SQLID}} PHV: {{PHV}}"
    }
   ]
  },
  {
   "title": "Total SQL exec per sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(SQL_EXECUTIONS_PER_SEC{job=\"$job\"})",
     "legendFormat": "SQL exec per sec"
    }
   ]
  },
  {
   "title": "Buffer gets per sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SQL_BG_PER_SEC{job=\"$job\"}>0",
     "legendFormat": "SQLID: {{SQLID}} PHV: {{PHV}}"
    }
   ]
  },
  {
   "title": "Buffer gets per Exec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SQL_BG_PER_EXEC{job=\"$job\"}",
     "legendFormat": "SQLID: {{SQLID}} PHV: {{PHV}}"
    }
   ]
  },
  {
   "title": "Activity CPU PER EXEC",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * CPU_PER_EXEC{job=\"$job\"} / ignoring(SQLID,PHV) group_left sum(CPU_PER_EXEC{job=\"$job\"}) without(SQLID,PHV)",
     "legendFormat": "SQLID: {{SQLID}} PHV: {{PHV}}"
    }
   ]
  },
  {
   "title": "Activity USERIOWAIT_PER_EXEC",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * USERIOWAIT_PER_EXEC{job=\"$job\"} / ignoring(SQLID,PHV) group_left sum(USERIOWAIT_PER_EXEC{job=\"$job\"}) without(SQLID,PHV)",
     "legendFormat": "SQLID: {{SQLID}} PHV: {{PHV}}"
    }
   ]
  },
  {
   "title": "Activity APPWAIT_PER_EXEC",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * APPWAIT_PER_EXEC{job=\"$job\"} / ignoring(SQLID,PHV) group_left sum(APPWAIT_PER_EXEC{job=\"$job\"}) without(SQLID,PHV)",
     "legendFormat": "SQLID: {{SQLID}} PHV: {{PHV}}"
    }
   ]
  },
  {
   "title": "Activity CONCURRENTCY_PER_EXEC",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * CONCURRENTCY_PER_EXEC{job=\"$job\"} / ignoring(SQLID,PHV) group_left sum(CONCURRENTCY_PER_EXEC{job=\"$job\"}) without(SQLID,PHV)",
     "legendFormat": "SQLID: {{SQLID}} PHV: {{PHV}}"
    }
   ]
  },
  {
   "title": "Activity SQL_EXEC_PER_SEC in %",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * SQL_EXECUTIONS_PER_SEC{job=\"$job\"} / ignoring(SQLID,PHV) group_left sum(SQL_EXECUTIONS_PER_SEC{job=\"$job\"}) without(SQLID,PHV)",
     "legendFormat": "SQLID: {{SQLID}} PHV: {{PHV}}"
    }
   ]
  },
  {
   "title": "Activity SQL_EXEC_PER_SEC",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SQL_EXECUTIONS_PER_SEC{job=\"$job\"}",
     "legendFormat": "SQLID: {{SQLID}} PHV: {{PHV}}"
    }
   ]
  }
 ]
}