{
 "title": "DB Size",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "tablespace",
    "label": "Tablespace",
    "query": {
     "query": "label_values({job=\"$job\"},TABLESPACE)"
    }
   },
   {
    "name": "segment_name",
    "label": "Segment name",
    "query": {
     "query": "label_values({job=\"$job\"},SEGMENT_NAME)"
    }
   },
   {
    "name": "owner",
    "label": "Owner",
    "query": {
     "query": "label_values({job=\"$job\"},OWNER)"
    }
   },
   {
    "name": "segment_type",
    "label": "Segment type",
    "query": {
     "query": "label_values({job=\"$job\"},SEGMENT_TYPE)"
    }
   },
   {
    "name": "partition_name",
    "label": "Partition name",
    "query": {
     "query": "label_values({job=\"$job\"},PARTITION_NAME)"
    }
   },
   {
    "name": "conid",
    "label": "Container ID",
    "query": {
     "query": "label_values({job=\"$job\"},CONID)"
    }
   }
  ]
 },
 "panels": [
  { "title": "non-CDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Search a segment BY Segment Name",
   "type": "timeseries",
   "description": "Search segment by Segment Name",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "DB_OBJECT_SIZE{job=\"$job\",SEGMENT_NAME=~\".*$segment_name\"}",
     "legendFormat": "{{SEGMENT_NAME}}/{{OWNER}}/{{TABLESPACE}}/{{SEGMENT_TYPE}}/{{PARTITION_NAME}}"
    }
   ]
  },
  {
   "title": "Search a segment By ALL Filters",
   "type": "timeseries",
   "description": "Search segment by Owner AND Tablespace AND Segment Name AND Segment Type AND Partition Name.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "DB_OBJECT_SIZE{job=\"$job\",SEGMENT_NAME=~\".*$segment_name\",OWNER=~\".*$owner\",PARTITION_NAME=~\".*$partition_name\",TABLESPACE=~\".*$tablespace\",SEGMENT_TYPE=~\".*$segment_type\"}",
     "legendFormat": "{{SEGMENT_NAME}}/{{OWNER}}/{{TABLESPACE}}/{{SEGMENT_TYPE}}/{{PARTITION_NAME}}"
    }
   ]
  },
  {
   "title": "Sum DataFiles",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DB_DATAFILE_SIZE{job=\"$job\"})",
     "legendFormat": "DB Size"
    }
   ]
  },
  {
   "title": "Sum DataFiles by Tablespaces",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DB_DATAFILE_SIZE{job=\"$job\"}) by (TABLESPACE)",
     "legendFormat": "{{TABLESPACE}}"
    }
   ]
  },
  {
   "title": "Sum Segments Size By Owner",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DB_OBJECT_SIZE{job=\"$job\"}) by (OWNER)",
     "legendFormat": "{{OWNER}}"
    }
   ]
  },
  {
   "title": "Sum Segments Size By Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DB_OBJECT_SIZE{job=\"$job\"}) by (SEGMENT_TYPE)",
     "legendFormat": "{{SEGMENT_TYPE}}"
    }
   ]
  },
  {
   "title": "Sum Segment Size By Segment name",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DB_OBJECT_SIZE{job=\"$job\"}) by (SEGMENT_NAME)",
     "legendFormat": "{{SEGMENT_NAME}}"
    }
   ]
  },
  {
   "title": "Sum DataFiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(DB_DATAFILE_SIZE{job=\"$job\"})",
     "legendFormat": "DB Size"
    }
   ]
  },
  {
   "title": "Sum DataFiles by Tablespaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(DB_DATAFILE_SIZE{job=\"$job\"}) by (TABLESPACE)",
     "legendFormat": "{{TABLESPACE}}"
    }
   ]
  },
  {
   "title": "Sum Segments Size By Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(DB_OBJECT_SIZE{job=\"$job\"}) by (SEGMENT_TYPE)",
     "legendFormat": "{{SEGMENT_TYPE}}"
    }
   ]
  },
  {
   "title": "Sum Segment Size By Segment name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(DB_OBJECT_SIZE{job=\"$job\"}) by (SEGMENT_NAME)",
     "legendFormat": "{{SEGMENT_NAME}}"
    }
   ]
  },
  {
   "title": "Datafile Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "DB_DATAFILE_SIZE{job=\"$job\"}",
     "legendFormat": "FiD:{{FILE_ID}}"
    }
   ]
  },
  {
   "title": "Datafile Size",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "DB_DATAFILE_SIZE{job=\"$job\"}",
     "legendFormat": "FiD:{{FILE_ID}}"
    }
   ]
  },
  {
   "title": "Multitenant",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Search segment BY  Segment Name",
     "type": "timeseries",
     "description": "Search segment BY  Segment Name",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "DB_OBJECT_SIZE{job=\"$job\",SEGMENT_NAME=~\".*$segment_name\"}",
       "legendFormat": "CiD:{{CONID}}/{{SEGMENT_NAME}}/{{OWNER}}/{{TABLESPACE}}/{{SEGMENT_TYPE}}/{{PARTITION_NAME}}"
      }
     ]
    },
    {
     "title": "Search a segment BY ALL Filters",
     "type": "timeseries",
     "description": "Search segment by Container ID AND Owner AND Tablespace AND Segment Name AND Segment Type AND PartitionName.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "DB_OBJECT_SIZE{job=\"$job\",SEGMENT_NAME=~\".*$segment_name\",CONID=~\".*$conid\",OWNER=~\".*$owner\",PARTITION_NAME=~\".*$partition_name\",TABLESPACE=~\".*$tablespace\",SEGMENT_TYPE=~\".*$segment_type\"}",
       "legendFormat": "CiD:{{CONID}}/{{SEGMENT_NAME}}/{{OWNER}}/{{TABLESPACE}}/{{SEGMENT_TYPE}}/{{PARTITION_NAME}}"
      },
      {
       "expr": "DB_OBJECT_SIZE{job=\"$job\",SEGMENT_NAME=~\".*$segment_name\"}",
       "legendFormat": "CiD:{{CONID}}/{{SEGMENT_NAME}}/{{OWNER}}/{{TABLESPACE}}/{{SEGMENT_TYPE}}/{{PARTITION_NAME}}"
      }
     ]
    },
    {
     "title": "Sum DataFiles by Container ID",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(DB_DATAFILE_SIZE{job=\"$job\"}) by (CONID)",
       "legendFormat": "Cid:{{CONID}}"
      }
     ]
    },
    {
     "title": "Sum DataFiles by Container ID and Tablespace",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 7, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(DB_DATAFILE_SIZE{job=\"$job\"}) by (CONID,TABLESPACE)",
       "legendFormat": "Cid:{{CONID}}/{{TABLESPACE}}"
      }
     ]
    },
    {
     "title": "Sum Segments Size By Owner and Container ID",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 7, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(DB_OBJECT_SIZE{job=\"$job\"}) by (OWNER,CONID)",
       "legendFormat": "Cid:{{CONID}}/{{OWNER}}"
      }
     ]
    },
    {
     "title": "Sum segment by Tablespace and Container ID",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(DB_OBJECT_SIZE{job=\"$job\"}) by (TABLESPACE,CONID)",
       "legendFormat": "Cid:{{CONID}}/{{TABLESPACE}}"
      }
     ]
    },
    {
     "title": "Sum Segment Size By Type and Container ID",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 7, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(DB_OBJECT_SIZE{job=\"$job\"}) by (SEGMENT_TYPE,CONID)",
       "legendFormat": "Cid:{{CONID}}/{{SEGMENT_TYPE}}"
      }
     ]
    },
    {
     "title": "Sum Segment Size By Segment name and Container ID",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 7, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(DB_OBJECT_SIZE{job=\"$job\"}) by (SEGMENT_NAME,CONID)",
       "legendFormat": "Cid:{{CONID}}/{{SEGMENT_NAME}}"
      }
     ]
    },
    {
     "title": "Sum segment by Tablespace and Container ID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(DB_OBJECT_SIZE{job=\"$job\"}) by (TABLESPACE,CONID)",
       "legendFormat": "Cid:{{CONID}}/{{TABLESPACE}}"
      }
     ]
    },
    {
     "title": "Sum Segment Size By Type and Container ID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(DB_OBJECT_SIZE{job=\"$job\"}) by (SEGMENT_TYPE,CONID)",
       "legendFormat": "Cid:{{CONID}}/{{SEGMENT_TYPE}}"
      }
     ]
    },
    {
     "title": "Sum Segment Size By Segment name",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(DB_OBJECT_SIZE{job=\"$job\",TABLESPACE!='UNDORBS11'}) by (SEGMENT_NAME)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sum Segment Size By Segment name and  Container ID",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 6, "x": 18, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(DB_OBJECT_SIZE{job=\"$job\"}) by (SEGMENT_NAME,CONID)",
       "legendFormat": "Cid{{CONID}}/{{SEGMENT_NAME}}"
      }
     ]
    },
    {
     "title": "Datafile Size",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "DB_DATAFILE_SIZE{job=\"$job\"}",
       "legendFormat": "CiD:{{CONID}} FiD:{{FILE_ID}}"
      }
     ]
    },
    {
     "title": "Size by Container ID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 7, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(DB_DATAFILE_SIZE{job=\"$job\"}) by (CONID)",
       "legendFormat": "CiD:{{CONID}}"
      }
     ]
    },
    {
     "title": "Sum Segment Size By Owner and Container ID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(DB_OBJECT_SIZE{job=\"$job\"}) by (OWNER,CONID)",
       "legendFormat": "Cid:{{CONID}}/{{OWNER}}"
      }
     ]
    },
    {
     "title": "Size by Container ID",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(DB_DATAFILE_SIZE{job=\"$job\"}) by (CONID)",
       "legendFormat": "CiD:{{CONID}}"
      }
     ]
    }
   ]
  }
 ]
}