{
 "title": "KPerf SQL details",
 "description": "KPerf SQL details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   { "name": "vjob", "label": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "vSQLID",
    "label": "SQLID",
    "query": {
     "query": "label_values({job=\"$vjob\"},SQLID)"
    }
   },
   {
    "name": "vPHV",
    "label": "PHV",
    "query": {
     "query": "label_values({SQLID=\"$vSQLID\"},PHV)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Buffer gets per sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SQL_BG_PER_SEC{job=~\"$vjob\",SQLID=\"$vSQLID\",PHV=\"$vPHV\"}",
     "legendFormat": "SQLID: {{SQLID}} PHV:{{PHV}}"
    }
   ]
  },
  {
   "title": "Buffer gets per Exec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SQL_BG_PER_EXEC{job=~\"$vjob\",SQLID=\"$vSQLID\",PHV=\"$vPHV\"}",
     "legendFormat": "SQLID: {{SQLID}} PHV: {{PHV}}"
    }
   ]
  },
  {
   "title": "SQL exec per sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SQL_EXECUTIONS_PER_SEC{job=~\"$vjob\",SQLID=\"$vSQLID\",PHV=\"$vPHV\"}",
     "legendFormat": "SQLID: {{SQLID}} PHV:{{PHV}}"
    }
   ]
  },
  {
   "title": "SQL CPU Time per exec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "CPU_PER_EXEC{job=~\"$vjob\",SQLID=\"$vSQLID\",PHV=\"$vPHV\"}",
     "legendFormat": "SQLD: {{SQLID}} PHV: {{PHV}}"
    }
   ]
  },
  {
   "title": "SQL User IO Wait Per Exec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "USERIOWAIT_PER_EXEC{job=~\"$vjob\",SQLID=\"$vSQLID\",PHV=\"$vPHV\"}",
     "legendFormat": "SQLID: {{SQLID}} PHV:{{PHV}}"
    }
   ]
  },
  {
   "title": "Elapsed time per Exec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "ELA_PER_EXEC{job=~\"$vjob\",SQLID=\"$vSQLID\",PHV=\"$vPHV\"}",
     "legendFormat": "SQLID: {{SQLID}} PHV: {{PHV}}"
    }
   ]
  },
  {
   "title": "SQL CONCURRENTCY Wait Time per exec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "CONCURRENTCY_PER_EXEC{job=~\"$vjob\",SQLID=\"$vSQLID\",PHV=\"$vPHV\"}",
     "legendFormat": "SQLD: {{SQLID}} PHV: {{PHV}}"
    }
   ]
  },
  {
   "title": "SQL App Wait Time per exec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "APPWAIT_PER_EXEC{job=~\"$vjob\",SQLID=\"$vSQLID\",PHV=\"$vPHV\"}",
     "legendFormat": "SQLD: {{SQLID}} PHV: {{PHV}}"
    }
   ]
  }
 ]
}